"""first

Revision ID: 4b292dee42e5
Revises: 
Create Date: 2023-04-12 23:05:49.460056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b292dee42e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('nm_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('brand', sa.String(), nullable=True),
                    sa.Column('brand_id', sa.Integer(), nullable=True),
                    sa.Column('site_brand_id', sa.Integer(), nullable=True),
                    sa.Column('supplier_id', sa.Integer(), nullable=True),
                    sa.Column('sale', sa.Integer(), nullable=True),
                    sa.Column('price', sa.String(), nullable=True),
                    sa.Column('sale_price', sa.String(), nullable=True),
                    sa.Column('rating', sa.Integer(), nullable=True),
                    sa.Column('feedbacks', sa.Integer(), nullable=True),
                    sa.Column('colors', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('nm_id')
                    )
    op.create_index(op.f('ix_product_nm_id'), 'product', ['nm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_nm_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
